import { CopyButton } from '@lobehub/ui';
import { Eye, EyeOff } from 'lucide-react';
import { type FC, useState } from 'react';
import { useTranslation } from 'react-i18next';

import { Button } from '@/components/ui/button';

interface ApiKeyDisplayProps {
  apiKey?: string;
}

/** Bullet run standing in for the hidden middle of the key. */
const MASK = '••••••••';

const ApiKeyDisplay: FC<ApiKeyDisplayProps> = ({ apiKey }) => {
  const { t } = useTranslation('auth');
  const [isVisible, setIsVisible] = useState(false);

  if (!apiKey) {
    return t('apikey.display.autoGenerated');
  }

  // Mask keeps the key's real prefix (e.g. `sk-ov-`) and its last 4 characters
  // so rows stay tellable apart while hidden; fall back to a full mask for
  // keys too short to safely reveal a tail.
  const prefixLength = apiKey.lastIndexOf('-') + 1;
  const prefix = apiKey.slice(0, prefixLength);
  const canShowTail = apiKey.length - prefixLength > 8;
  const displayValue = isVisible
    ? apiKey
    : canShowTail
      ? `${prefix}${MASK}${apiKey.slice(-4)}`
      : `${prefix}${MASK}`;

  return (
    <div className="flex items-center gap-1">
      <span className="truncate whitespace-nowrap font-mono text-xs">{displayValue}</span>
      <Button
        aria-label={isVisible ? t('apikey.display.hide') : t('apikey.display.show')}
        size="icon-sm"
        title={isVisible ? t('apikey.display.hide') : t('apikey.display.show')}
        type="button"
        variant="ghost"
        onClick={() => setIsVisible(!isVisible)}
      >
        {isVisible ? <EyeOff /> : <Eye />}
      </Button>
      <CopyButton content={apiKey} size={'small'} title={t('apikey.display.copy')} />
    </div>
  );
};

export default ApiKeyDisplay;
