from pathlib import Path

root=Path.cwd()

def rep(path, old, new):
 p=root/path; s=p.read_text(); assert s.count(old)==1,(path,s.count(old),old[:80]); p.write_text(s.replace(old,new))

rep('apps/server/src/services/task/index.ts', "import { collapseActivityLog } from './collapseActivityLog';", "import { collapseActivityLog } from './collapseActivityLog';\nimport { buildInterruptedTaskGeneration } from './interruptedGeneration';")
rep('apps/server/src/services/task/index.ts', '''      try {\n        await this.taskModel.recoverInterruptedRun({\n          currentTopicId: snapshot.currentTopicId ?? null,\n          id: snapshot.id,\n          operationId: topic.operationId ?? null,\n          reservationId: snapshot.runReservationId ?? null,\n          topicId: topic.topicId,\n        });\n      } catch (error) {''', '''      const generation = buildInterruptedTaskGeneration(snapshot, topic);\n      if (!generation) continue;\n      try {\n        await this.taskModel.recoverInterruptedRun(generation);\n      } catch (error) {''')

rep('packages/database/src/models/task.ts', "import { TaskDependencyError } from './taskDependency';", "import { TaskDependencyError } from './taskDependency';\nimport { shouldParkInterruptedTask } from './interruptedRunFence';")
rep('packages/database/src/models/task.ts', '''    await new TaskTopicModel(this.db, this.userId, this.workspaceId).cancelIfRunning(\n      input.id,\n      input.topicId,\n    );\n    if (input.currentTopicId !== null && input.currentTopicId !== input.topicId) return false;\n    const recovered = await this.db\n      .update(tasks)''', '''    await new TaskTopicModel(this.db, this.userId, this.workspaceId).cancelIfRunning(\n      input.id,\n      input.topicId,\n    );\n    // A stopped historical/non-current topic must never inherit the task's\n    // current reservation. Only the exact current topic generation may park\n    // task-level state; otherwise recovery is topic-local.\n    const [taskState] = await this.db\n      .select({\n        currentTopicId: tasks.currentTopicId,\n        runReservationId: tasks.runReservationId,\n        status: tasks.status,\n      })\n      .from(tasks)\n      .where(and(eq(tasks.id, input.id), this.ownership()))\n      .for('update');\n    if (!taskState || !shouldParkInterruptedTask(taskState, input)) return false;\n    const recovered = await this.db\n      .update(tasks)''')
rep('packages/database/src/models/task.ts', '''          input.currentTopicId === null\n            ? isNull(tasks.currentTopicId)\n            : eq(tasks.currentTopicId, input.currentTopicId),\n          input.reservationId === null\n            ? isNull(tasks.runReservationId)\n            : eq(tasks.runReservationId, input.reservationId),''', '''          eq(tasks.currentTopicId, input.currentTopicId!),\n          input.reservationId === null\n            ? isNull(tasks.runReservationId)\n            : eq(tasks.runReservationId, input.reservationId),''')

rep('src/store/task/slices/detail/action.ts', "import { taskKeys } from '@/libs/swr/keys';", "import { taskKeys } from '@/libs/swr/keys';\n\nimport { resolveTaskDetailPolling } from './pollingPolicy';")
rep('src/store/task/slices/detail/action.ts', '''    return useClientPollingSWR(\n      taskId ? taskKeys.detail(taskId) : null,\n      async ([, id]: [string, string]) => this.fetchTaskDetail(id),\n      {\n        dedupingInterval: 1_000,\n        refreshInterval: shouldPoll ? TASK_DETAIL_POLL_INTERVAL : taskId ? 15_000 : 0,\n      },\n    );''', '''    const polling = resolveTaskDetailPolling(Boolean(taskId), shouldPoll);\n    return useClientPollingSWR(\n      taskId ? taskKeys.detail(taskId) : null,\n      async ([, id]: [string, string]) => this.fetchTaskDetail(id),\n      polling,\n    );''')
rep('src/store/task/slices/detail/action.test.ts', '''      dedupingInterval: 1_000,\n      refreshInterval: 15_000,''', '''      dedupingInterval: 15_000,\n      refreshInterval: 15_000,''')
rep('src/store/task/slices/detail/action.test.ts', '''      dedupingInterval: 1_000,\n      refreshInterval: 0,''', '''      dedupingInterval: 0,\n      refreshInterval: 0,''')

# Make the real-SWR regression prove dedupe across the whole idle cadence.
rep('src/store/task/slices/detail/polling.test.tsx', '''    await act(async () => {\n      await vi.advanceTimersByTimeAsync(50);\n    });\n    expect(taskService.getDetail).toHaveBeenCalledTimes(1);\n    await act(async () => {\n      await vi.advanceTimersByTimeAsync(15_000);\n    });''', '''    await act(async () => {\n      await vi.advanceTimersByTimeAsync(50);\n    });\n    expect(taskService.getDetail).toHaveBeenCalledTimes(1);\n    // A second subscriber arriving anywhere inside the 15s idle cadence must\n    // share the existing request/cache rather than create another transport.\n    await act(async () => {\n      await vi.advanceTimersByTimeAsync(5_000);\n    });\n    expect(taskService.getDetail).toHaveBeenCalledTimes(1);\n    await act(async () => {\n      await vi.advanceTimersByTimeAsync(10_000);\n    });''')
