from pathlib import Path
r=Path.cwd()
def rep(path,old,new):
 p=r/path;s=p.read_text();assert s.count(old)==1,(path,s.count(old),old[:100]);p.write_text(s.replace(old,new))
rep('packages/database/src/models/task.ts','  private async lockDependencyGraph(): Promise<void> {','  async lockDependencyGraph(): Promise<void> {')
old='''    const [interrupted] = await this.db\n      .select({ id: taskTopics.id })\n      .from(taskTopics)\n      .where(\n        and(\n          eq(taskTopics.taskId, input.id),\n          eq(taskTopics.topicId, input.topicId),\n          input.operationId === null\n            ? isNull(taskTopics.operationId)\n            : eq(taskTopics.operationId, input.operationId),\n          inArray(taskTopics.status, ['running', 'canceled']),\n          this.topicsOwnership(),\n        ),\n      )\n      .for('update');\n    if (!interrupted) return false;\n    await new TaskTopicModel(this.db, this.userId, this.workspaceId).cancelIfRunning(\n      input.id,\n      input.topicId,\n    );\n    // A stopped historical/non-current topic must never inherit the task's\n    // current reservation. Only the exact current topic generation may park\n    // task-level state; otherwise recovery is topic-local.\n    const [taskState] = await this.db\n      .select({\n        currentTopicId: tasks.currentTopicId,\n        runReservationId: tasks.runReservationId,\n        status: tasks.status,\n      })\n      .from(tasks)\n      .where(and(eq(tasks.id, input.id), this.ownership()))\n      .for('update');\n    if (!taskState || !shouldParkInterruptedTask(taskState, input)) return false;'''
new='''    // Lock and validate task generation before mutating its topic. A successor\n    // may reuse the same topic between interruption and compensation; checking\n    // the topic first could cancel that successor before the reservation fence\n    // notices it. Lock order is graph -> task -> topic everywhere.\n    const [taskState] = await this.db\n      .select({\n        currentTopicId: tasks.currentTopicId,\n        runReservationId: tasks.runReservationId,\n        status: tasks.status,\n      })\n      .from(tasks)\n      .where(and(eq(tasks.id, input.id), this.ownership()))\n      .for('update');\n    if (!taskState) return false;\n    const parksTask = shouldParkInterruptedTask(taskState, input);\n    if (input.currentTopicId !== null && !parksTask) return false;\n    if (input.currentTopicId === null && taskState.currentTopicId === input.topicId) return false;\n\n    const [interrupted] = await this.db\n      .select({ id: taskTopics.id })\n      .from(taskTopics)\n      .where(\n        and(\n          eq(taskTopics.taskId, input.id),\n          eq(taskTopics.topicId, input.topicId),\n          input.operationId === null\n            ? isNull(taskTopics.operationId)\n            : eq(taskTopics.operationId, input.operationId),\n          inArray(taskTopics.status, ['running', 'canceled']),\n          this.topicsOwnership(),\n        ),\n      )\n      .for('update');\n    if (!interrupted) return false;\n    await new TaskTopicModel(this.db, this.userId, this.workspaceId).cancelIfRunning(\n      input.id,\n      input.topicId,\n    );\n    if (!parksTask) return false;'''
rep('packages/database/src/models/task.ts',old,new)
rep('apps/server/src/services/task/index.ts','''        const taskModel = new TaskModel(tx, this.userId, this.workspaceId);\n        const taskTopicModel = new TaskTopicModel(tx, this.userId, this.workspaceId);\n\n        // Cancel by the frozen id set rather than the pre-read topic list, so a\n        // topic that started between the snapshot and this transaction is still\n        // closed together with the status update.\n        canceledTopics = await taskTopicModel.cancelRunningByTaskIds(targetIds);''','''        const taskModel = new TaskModel(tx, this.userId, this.workspaceId);\n        const taskTopicModel = new TaskTopicModel(tx, this.userId, this.workspaceId);\n\n        // Establish the graph lock before touching topic rows. Recovery also\n        // starts with this advisory lock, so concurrent cascade/recovery paths\n        // cannot form a topic-row <-> graph-lock cycle.\n        await taskModel.lockDependencyGraph();\n        // Cancel by the frozen id set rather than the pre-read topic list, so a\n        // topic that started between the snapshot and this transaction is still\n        // closed together with the status update.\n        canceledTopics = await taskTopicModel.cancelRunningByTaskIds(targetIds);''')
p=r/'packages/database/src/models/__tests__/taskInterruptedRun.test.ts';s=p.read_text();marker="  it('does not alter another owner task or topic', async () => {";assert s.count(marker)==1
case='''  it('does not cancel a successor that has reused the interrupted topic', async () => {\n    const input = await seed();\n    await db.update(tasks).set({ runReservationId: 'run-2' }).where(eq(tasks.id, input.id));\n    await db.update(taskTopics).set({ status: 'running' }).where(eq(taskTopics.taskId, input.id));\n    expect(await model.recoverInterruptedRun(input)).toBe(false);\n    expect(await model.findById(input.id)).toMatchObject({ currentTopicId: 'topic-1', runReservationId: 'run-2', status: 'running' });\n    expect((await topicModel.findByTaskId(input.id))[0].status).toBe('running');\n  });\n\n''';p.write_text(s.replace(marker,case+marker))
p=r/'apps/server/src/services/task/index.test.ts';s=p.read_text();needle='    recoverInterruptedRun: vi.fn().mockResolvedValue(true),';assert s.count(needle)==1;s=s.replace(needle,needle+'\n    lockDependencyGraph: vi.fn().mockResolvedValue(undefined),');marker="  describe('interrupted state-change recovery', () => {";assert s.count(marker)==1
case='''  describe('dependency lock ordering', () => {\n    it('acquires the graph lock before touching running topic rows in a cascade', async () => {\n      const order: string[] = [];\n      mockTaskModel.resolve.mockResolvedValue({ id: 'task-1', identifier: 'T-1', status: 'running' });\n      mockTaskModel.findAllDescendants.mockResolvedValue([]);\n      mockTaskModel.lockDependencyGraph.mockImplementation(async () => { order.push('graph'); });\n      mockTaskTopicModel.cancelRunningByTaskIds.mockImplementation(async () => { order.push('topics'); return []; });\n      mockTaskModel.updateStatusForIds.mockResolvedValue([{ id: 'task-1', status: 'paused' }]);\n      db.transaction = vi.fn(async (fn: any) => fn(db)) as any;\n      await new TaskService(db, userId).updateStatusCascade({ id: 'T-1', status: 'paused' });\n      expect(order.slice(0, 2)).toEqual(['graph', 'topics']);\n    });\n  });\n\n''';p.write_text(s.replace(marker,case+marker))
