server {
    listen 80;
    server_name device-gateway.aspectlylabs.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name device-gateway.aspectlylabs.com;
    ssl_certificate /etc/nginx/ssl/aspectlylabs.com/origin.pem;
    ssl_certificate_key /etc/nginx/ssl/aspectlylabs.com/origin.key;

    location / {
        proxy_pass http://127.0.0.1:28788;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
        proxy_buffering off;
    }
}
