import { DEFAULT_ONBOARDING_MODEL, DEFAULT_ONBOARDING_PROVIDER } from '@orvilo/business-const';

export const ONBOARDING_PRODUCTION_DEFAULT_MODEL = {
  model: DEFAULT_ONBOARDING_MODEL,
  provider: DEFAULT_ONBOARDING_PROVIDER,
} as const;
