contact_links:
  - name: Ask a question for self-hosting
    url: https://github.com/alexj11324/orvilo1/discussions/new?category=q-a
    about: Please post questions, and ideas in discussions.
  - name: Questions and ideas
    url: https://github.com/alexj11324/orvilo1/discussions/new/choose
    about: Please post questions, and ideas in discussions.
