import { chromium } from 'playwright';
const browser = await chromium.connectOverCDP('http://localhost:9222');
const ctx = browser.contexts()[0];
const page = await ctx.newPage();
await page.setViewportSize({ width: 1440, height: 900 });
await page.goto('http://localhost:3010/agent-testing/inbox', { waitUntil: 'domcontentloaded' });
await page.waitForTimeout(12000);
console.log('URL:', page.url());
await page.screenshot({ path: '/tmp/parity-inbox-evidence/orvilo-inbox-2.png' });
const txt = await page.evaluate(() => document.body.innerText.slice(0, 1500));
console.log('TEXT:', txt);
await page.close();
await browser.close();
