import type { GenerateObjectSchema } from '@orvilo/model-runtime';
import { z } from 'zod';

/**
 * The coordinator contract is shared by the model-backed planner, the worker,
 * and the user-facing apply endpoint. Keeping one parser at this boundary
 * prevents a proposal accepted by the API from being a different shape than
 * the one generated by the coordinator.
 */
export const taskPlanningActionSchema = z.discriminatedUnion('action', [
  z.object({
    action: z.literal('assign_task'),
    assigneeAgentId: z.string().nullable().optional(),
    assigneeUserId: z.string().nullable().optional(),
    reason: z.string().trim().min(1).max(8_000),
    taskId: z.string().min(1),
  }),
  z.object({
    action: z.literal('create_task'),
    description: z.string().max(8_000),
    instruction: z.string().min(1).max(50_000),
    name: z.string().trim().min(1).max(255),
    parentTaskId: z.string().nullable().optional(),
    priority: z.number().int().min(0).max(4).optional(),
    projectId: z.string().min(1),
    reason: z.string().trim().min(1).max(8_000),
  }),
  z.object({
    action: z.literal('escalate'),
    reason: z.string().trim().min(1).max(8_000),
  }),
  z.object({
    action: z.literal('noop'),
    reason: z.string().trim().min(1).max(8_000),
  }),
  z.object({
    action: z.literal('request_stop'),
    reason: z.string().trim().min(1).max(8_000),
    taskId: z.string().min(1),
  }),
  z.object({
    action: z.literal('set_dependency'),
    dependsOnTaskId: z.string().min(1),
    operation: z.enum(['add', 'remove']),
    reason: z.string().trim().min(1).max(8_000),
    taskId: z.string().min(1),
  }),
  z.object({
    action: z.literal('update_task'),
    patch: z
      .object({
        instruction: z.string().min(1).max(50_000).optional(),
        name: z.string().trim().min(1).max(255).optional(),
        priority: z.number().int().min(0).max(4).optional(),
      })
      .refine((patch) => Object.keys(patch).length > 0, 'Task patch cannot be empty'),
    reason: z.string().trim().min(1).max(8_000),
    taskId: z.string().min(1),
  }),
]);

export const taskPlanningProposalSchema = z.object({
  actions: z.array(taskPlanningActionSchema).max(50),
  explanation: z.string().trim().min(1).max(20_000),
  requiresApproval: z.boolean(),
});

/** JSON Schema sent to providers that support structured generation. */
export const taskPlanningProposalJsonSchema = {
  name: 'linear_task_planning_proposal',
  schema: {
    additionalProperties: false,
    properties: {
      actions: {
        items: {
          oneOf: [
            {
              additionalProperties: false,
              properties: {
                action: { const: 'assign_task', type: 'string' },
                assigneeAgentId: { type: ['string', 'null'] },
                assigneeUserId: { type: ['string', 'null'] },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
                taskId: { minLength: 1, type: 'string' },
              },
              required: ['action', 'taskId', 'reason', 'assigneeAgentId', 'assigneeUserId'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'create_task', type: 'string' },
                description: { maxLength: 8_000, type: 'string' },
                instruction: { maxLength: 50_000, minLength: 1, type: 'string' },
                name: { maxLength: 255, minLength: 1, type: 'string' },
                parentTaskId: { type: ['string', 'null'] },
                priority: { maximum: 4, minimum: 0, type: 'integer' },
                projectId: { minLength: 1, type: 'string' },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
              },
              required: ['action', 'name', 'description', 'instruction', 'projectId', 'reason'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'escalate', type: 'string' },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
              },
              required: ['action', 'reason'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'noop', type: 'string' },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
              },
              required: ['action', 'reason'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'request_stop', type: 'string' },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
                taskId: { minLength: 1, type: 'string' },
              },
              required: ['action', 'taskId', 'reason'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'set_dependency', type: 'string' },
                dependsOnTaskId: { minLength: 1, type: 'string' },
                operation: { enum: ['add', 'remove'], type: 'string' },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
                taskId: { minLength: 1, type: 'string' },
              },
              required: ['action', 'taskId', 'dependsOnTaskId', 'operation', 'reason'],
              type: 'object',
            },
            {
              additionalProperties: false,
              properties: {
                action: { const: 'update_task', type: 'string' },
                patch: {
                  additionalProperties: false,
                  properties: {
                    instruction: { maxLength: 50_000, minLength: 1, type: 'string' },
                    name: { maxLength: 255, minLength: 1, type: 'string' },
                    priority: { maximum: 4, minimum: 0, type: 'integer' },
                  },
                  type: 'object',
                },
                reason: { maxLength: 8_000, minLength: 1, type: 'string' },
                taskId: { minLength: 1, type: 'string' },
              },
              required: ['action', 'taskId', 'patch', 'reason'],
              type: 'object',
            },
          ],
          type: 'object',
        },
        maxItems: 50,
        type: 'array',
      },
      explanation: { maxLength: 20_000, minLength: 1, type: 'string' },
      requiresApproval: { type: 'boolean' },
    },
    required: ['actions', 'explanation', 'requiresApproval'],
    type: 'object' as const,
  },
  strict: true,
} satisfies GenerateObjectSchema;
