export const HATCHET_TASK_NAMES = {
  agentStep: 'orvilo-agent-step',
  agentSignalNightlySchedule: 'orvilo-agent-signal-nightly-schedule',
  collaborationOutboxSweep: 'orvilo-collaboration-outbox-sweep',
  goalAdvance: 'orvilo-goal-advance',
  goalSweep: 'orvilo-goal-sweep',
  linearSyncSweep: 'orvilo-linear-sync-sweep',
  taskHeartbeat: 'orvilo-task-heartbeat',
  taskScheduleDispatch: 'orvilo-task-schedule-dispatch',
  taskScheduleExecute: 'orvilo-task-schedule-execute',
  taskScheduledTopicDispatch: 'orvilo-task-scheduled-topic-dispatch',
  taskWatchdog: 'orvilo-task-watchdog',
  verifySweep: 'orvilo-verify-sweep',
  workflowDispatch: 'orvilo-workflow-dispatch',
  workflowDispatchSweep: 'orvilo-workflow-dispatch-sweep',
} as const;
