import { DEFAULT_FEATURE_FLAGS, mapFeatureFlagsEnvToState } from '@/config/featureFlags';

export const PREVIEW_USER_ID = 'ui-preview-user';
export const previewWorkspace = {
  id: 'preview-workspace',
  slug: 'preview',
  name: 'Orvilo UI preview',
  ownerId: PREVIEW_USER_ID,
  avatar: null,
  description: 'Local fixtures only — no backend connection',
  role: 'owner',
  plan: 'free',
  memberCount: 1,
  createdAt: new Date('2026-10-07'),
  updatedAt: new Date('2026-10-07'),
  settings: {},
  metadata: {},
};
export const PREVIEW_STORAGE_KEY = 'orvilo:repository-ui-preview:v1';
export const PREVIEW_REVISION = 'f81bd916e59a6256651ac4301962b8afb7b6e9fd';
export const now = new Date('2026-10-07T15:00:00Z');
export const previewUser = {
  id: PREVIEW_USER_ID,
  name: 'Alex · Preview',
  username: 'alex-preview',
  email: 'preview@example.invalid',
};
export const serverConfig = {
  aiProvider: {},
  telemetry: {},
  enableBusinessFeatures: false,
  enableGatewayMode: false,
  enableUploadFileToServer: false,
  enableComposio: false,
  enableOrviloSkill: false,
};
export const featureFlags = {
  ...DEFAULT_FEATURE_FLAGS,
  workspace: true,
  check_updates: false,
  market: false,
  cloud_promotion: false,
  dev_dock: false,
};
export const runtimeConfig = {
  serverConfig,
  serverFeatureFlags: mapFeatureFlagsEnvToState(featureFlags),
  billboard: null,
};

export const createAgent = (id: string, name: string, slug = id) => ({
  id,
  slug,
  name,
  title: name,
  description: '',
  avatar: null,
  backgroundColor: null,
  userId: PREVIEW_USER_ID,
  workspaceId: 'preview-workspace',
  visibility: 'public',
  virtual: false,
  createdAt: now,
  updatedAt: now,
  pinned: false,
  tags: [],
  plugins: [],
  model: 'preview',
  provider: 'orvilo',
  params: {},
  chatConfig: {},
  systemRole: '',
  clientId: null,
  metadata: {},
  agencyConfig: {
    enabled: true,
    executionTarget: 'device',
    boundDeviceId: 'preview-device',
    heterogeneousProvider: {
      type: id === 'preview-agent-b' ? 'codex' : 'orvilo',
      model: 'preview',
    },
  },
});

export function createInitialDatabase() {
  const agents = [
    createAgent('preview-agent-a', 'Orvilo AI', 'inbox'),
    createAgent('preview-agent-b', 'Agent B'),
    createAgent('preview-agent-c', 'Agent C'),
  ];
  const names = [
    ['Keep the navigation width consistent', 'in_progress'],
    ['Refine the new conversation flow', 'in_progress'],
    ['Separate web and desktop actions', 'in_review'],
    ['Make issue properties keyboard accessible', 'todo'],
    ['Improve project empty states', 'backlog'],
    ['Connect automation triggers', 'backlog'],
    ['Move agent configuration into Settings', 'done'],
    ['Remember the last selected agent', 'done'],
    ['Show the Device picker only when needed', 'todo'],
  ];
  const tasks = names.map(([name, workflowCategory], i) => ({
    id: `preview-task-${i + 1}`,
    identifier: `UI-${101 + i}`,
    seq: 101 + i,
    name,
    instruction: `## ${name}\n\nUse the existing Orvilo components and keep the Web and Desktop boundaries explicit.\n\n- Preserve keyboard navigation.\n- Verify the populated and empty states.\n- Check both light and dark themes.`,
    description: 'Repository UI review · local fixture',
    editorData: null,
    status: workflowCategory === 'done' ? 'completed' : 'backlog',
    workflowCategory,
    workflowStateRefId: null,
    workflowStateId: null,
    domainRevision: 1,
    requirementRevision: 1,
    policyRevision: 1,
    executionGeneration: 0,
    createdByUserId: PREVIEW_USER_ID,
    userId: PREVIEW_USER_ID,
    createdByAgentId: null,
    createdByKind: 'user',
    createdBySubjectId: PREVIEW_USER_ID,
    createdBySnapshot: null,
    assigneeAgentId: i % 3 === 0 ? agents[0].id : null,
    assigneeUserId: i % 3 === 1 ? PREVIEW_USER_ID : null,
    assigneeAgent: i % 3 === 0 ? agents[0] : null,
    assigneeUser: i % 3 === 1 ? { ...previewUser, fullName: previewUser.name, avatar: null } : null,
    reviewerUserId: workflowCategory === 'in_review' ? PREVIEW_USER_ID : null,
    projectId: i < 6 ? 'preview-project' : null,
    project: null,
    workspaceId: 'preview-workspace',
    teamId: null,
    visibility: 'public',
    priority: (i % 3) + 1,
    parentTaskId: null as string | null,
    parentIdentifier: null,
    duplicateOfTaskId: null,
    cycleRefId: null,
    projectMilestoneId: null,
    labels: [],
    tags: [],
    subtaskCount: 0,
    commentCount: 0,
    automationMode: null,
    schedulePattern: null,
    heartbeatInterval: null,
    nextRunAt: null,
    createdAt: new Date(now.getTime() - i * 3600000),
    updatedAt: now,
    position: (i + 1) * 1000,
    config: {},
    context: {},
    metadata: {},
    assignmentMode: 'manual',
    orchestrationOwner: 'human',
    isArchived: false,
  }));
  return {
    version: 1,
    tasks,
    agents,
    projects: [
      {
        id: 'preview-project',
        identifier: 'UI',
        slug: 'workspace-experience',
        name: 'Workspace experience',
        description: 'Refine the human and agent workspace using existing Orvilo components.',
        status: 'active',
        color: null,
        icon: null,
        avatar: null,
        backgroundColor: null,
        visibility: 'public',
        userId: PREVIEW_USER_ID,
        workspaceId: 'preview-workspace',
        createdAt: now,
        updatedAt: now,
        metadata: {},
        config: {},
        teamIds: [],
        members: [],
      },
    ],
    topics: [
      {
        id: 'preview-topic',
        agentId: agents[0].id,
        title: 'Review the workspace experience',
        createdAt: now,
        updatedAt: now,
        status: 'active',
        favorite: false,
        historySummary: null,
        metadata: {},
        trigger: 'user',
        userId: PREVIEW_USER_ID,
        workspaceId: 'preview-workspace',
        groupId: null,
      },
    ],
    messages: [
      {
        id: 'preview-message-1',
        topicId: 'preview-topic',
        agentId: agents[0].id,
        role: 'user',
        content: 'Review our workspace UI without replacing the existing components.',
        createdAt: now,
        updatedAt: now,
        parentId: null,
        meta: {},
        extra: {},
      },
      {
        id: 'preview-message-2',
        topicId: 'preview-topic',
        agentId: agents[0].id,
        role: 'assistant',
        content:
          'This preview uses the repository’s real conversation components.\n\nThe Sidebar, Issues, Projects, and Settings retain their original routing and state management. Only the data transport is simulated locally.\n\n**No real agent execution or backend connection occurs in this preview.**',
        createdAt: now,
        updatedAt: now,
        parentId: 'preview-message-1',
        model: 'preview',
        provider: 'orvilo',
        meta: {},
        extra: {},
      },
    ],
    userState: {
      userId: PREVIEW_USER_ID,
      email: previewUser.email,
      fullName: previewUser.name,
      username: previewUser.username,
      avatar: '',
      firstName: 'Alex',
      lastName: '',
      isFreePlan: true,
      isOnboard: true,
      canEnablePWAGuide: false,
      canEnableTrace: false,
      hasConversation: true,
      onboarding: { currentStep: 5, finishedAt: now.toISOString(), version: 1 },
      preference: {},
      settings: {
        general: {
          themeMode: 'light',
          language: 'en-US',
          responseLanguage: 'en-US',
          timezone: 'America/New_York',
          telemetry: false,
        },
      },
    },
  };
}
export type PreviewDatabase = ReturnType<typeof createInitialDatabase>;
