import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');

const mobileHtmlPath = path.resolve(root, 'dist/mobile/index.mobile.html');
const mobileHtmlFallbackPath = path.resolve(root, 'dist/mobile/index.html');
const hasMobileBuild = existsSync(mobileHtmlPath) || existsSync(mobileHtmlFallbackPath);

let output: string;

if (hasMobileBuild) {
  // Docker: mobile build exists locally, inline the template
  const mobileHtml = readFileSync(
    existsSync(mobileHtmlPath) ? mobileHtmlPath : mobileHtmlFallbackPath,
    'utf8',
  );

  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const mobileHtmlTemplate = ${JSON.stringify(mobileHtml)};
`;
} else {
  // Vercel: no mobile build, re-export the pre-committed source file
  output = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export { mobileHtmlTemplate } from './mobileHtmlTemplate.source';
`;
}

writeFileSync(
  path.resolve(root, 'src/app/spa/[variants]/[[...path]]/spaHtmlTemplates.ts'),
  output,
  'utf8',
);

console.log(`Generated spaHtmlTemplates.ts (mobile from ${hasMobileBuild ? 'build' : 'source'})`);

const authHtmlPath = path.resolve(root, 'dist/auth/index.auth.html');

if (existsSync(authHtmlPath)) {
  const authHtml = readFileSync(authHtmlPath, 'utf8');

  const authOutput = `// Auto-generated by scripts/generateSpaTemplates.mts after vite build
// Do not edit manually

export const authHtmlTemplate = ${JSON.stringify(authHtml)};
`;

  writeFileSync(path.resolve(root, 'src/app/spa-auth/authHtmlTemplate.ts'), authOutput, 'utf8');

  console.log('Generated authHtmlTemplate.ts');
} else {
  console.log('Skipped authHtmlTemplate.ts (no dist/auth build)');
}
