#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# ── Wizard-local helpers ───────────────────────────────────────────────────

# vercel_env KEY VALUE TARGET [BRANCH] — upsert a Vercel env var via REST API.
vercel_env() {
  local key="$1" value="$2" target="$3" branch="${4:-}"
  if [[ -z "${VERCEL_TOKEN:-}" || -z "${VERCEL_PROJECT_ID:-}" ]]; then
    SKIPPED+=("Vercel env $key [$target]")
    warn "缺少 VERCEL_TOKEN/PROJECT_ID，跳过 $key —— 之后手动在 Vercel 后台添加"
    return
  fi
  local qs="upsert=true"
  [[ -n "${VERCEL_ORG_ID:-}" ]] && qs="${qs}&teamId=${VERCEL_ORG_ID}"
  local payload
  if [[ -n "$branch" ]]; then
    payload=$(jq -n --arg k "$key" --arg v "$value" --arg t "$target" --arg b "$branch" \
      '{key:$k, value:$v, type:"encrypted", target:[$t], gitBranch:$b}')
  else
    payload=$(jq -n --arg k "$key" --arg v "$value" --arg t "$target" \
      '{key:$k, value:$v, type:"encrypted", target:[$t]}')
  fi
  if curl -fsS -X POST \
      "https://api.vercel.com/v10/projects/${VERCEL_PROJECT_ID}/env?${qs}" \
      -H "Authorization: Bearer ${VERCEL_TOKEN}" \
      -H 'Content-Type: application/json' \
      -d "$payload" >/dev/null; then
    printf '  %s✓ 写入%s Vercel env %s [%s%s]\n' "$GREEN" "$RESET" "$key" "$target" "${branch:+ @$branch}"
  else
    SKIPPED+=("Vercel env $key [$target]")
    warn "写入 $key 失败 —— 之后在 Vercel 后台手动添加"
  fi
}

# try_pg URL SQL — run SQL against a specific connection URL (psql → bun+pg).
try_pg() {
  local url="$1" sql="$2"
  if command -v psql >/dev/null 2>&1; then
    psql "$url" -v ON_ERROR_STOP=1 -tAc "$sql"
    return
  fi
  if [[ -d node_modules ]]; then
    PG_SQL="$sql" DB_URL="$url" bun -e '
      import pg from "pg";
      const c = new pg.Client({ connectionString: process.env.DB_URL });
      await c.connect();
      await c.query(process.env.PG_SQL);
      await c.end();
    '
    return
  fi
  return 1
}

# pg_admin SQL — run SQL against PREVIEW_DB_ADMIN_URL.
pg_admin() { try_pg "$PREVIEW_DB_ADMIN_URL" "$1"; }

# app_db_url DBNAME — derive an app connection string from the admin URL.
app_db_url() {
  echo "$PREVIEW_DB_ADMIN_URL" | sed -E "s|/[^/?]+(\?.*)?\$|/$1\1|"
}

banner "Orvilo 云开发环境迁移"

# ── Stage 1 · 前置检查 + Vercel link ────────────────────────────────────────
stage "前置检查 + 连接 Vercel 项目"
say "检查本机工具，并把仓库 link 到 Vercel project。"
for cmd in gh bun curl jq; do
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$cmd"
  else
    warn "缺少 $cmd"
    SKIPPED+=("install $cmd")
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "gh 未登录 —— 先跑 gh auth login，否则 GitHub secrets 只能手动设置"
fi
if ! command -v vercel >/dev/null 2>&1; then
  say "未找到 vercel CLI，尝试通过 bun 安装…"
  bun install -g vercel@latest || warn "vercel CLI 安装失败"
fi
if [[ ! -f .vercel/project.json ]]; then
  say "把当前目录 link 到 Vercel project（还没有 project 就先在网页端 Import：）"
  open_url "https://vercel.com/new"
  step "Import alexj11324/orvilo1 → Root Directory 保持仓库根目录"
  step "Framework 选 Next.js（自动识别）；Production Branch = main"
  pause "project 建好后按 Enter，我会执行 vercel link"
  vercel link --yes || warn "vercel link 失败，请手动跑 vercel link"
fi
if [[ -f .vercel/project.json ]]; then
  VERCEL_ORG_ID=$(jq -r '.orgId' .vercel/project.json)
  VERCEL_PROJECT_ID=$(jq -r '.projectId' .vercel/project.json)
  say "已连接：orgId=${VERCEL_ORG_ID} projectId=${VERCEL_PROJECT_ID}"
fi
open_url "https://vercel.com/account/tokens"
step "创建一个 Account-scoped token（名字随意，如 orvilo-ci）"
ask_secret VERCEL_TOKEN "粘贴 Vercel token："

# ── Stage 2 · Deployment Protection 绕过密钥 ────────────────────────────────
stage "Deployment Protection（Preview 自动化绕过）"
say "Preview 部署默认有登录保护，CI 里的 Playwright 需要 bypass secret。"
open_url "https://vercel.com"
step "Project → Settings → Deployment Protection"
step "确认 'Vercel Authentication' 对 Preview 开启"
step "在 'Protection Bypass for Automation' 生成一个 secret"
ask_secret VERCEL_AUTOMATION_BYPASS_SECRET "粘贴 bypass secret："
set_secret VERCEL_AUTOMATION_BYPASS_SECRET "$VERCEL_AUTOMATION_BYPASS_SECRET"

# ── Stage 3 · 远程 ParadeDB ─────────────────────────────────────────────────
stage "远程 ParadeDB（pgvector + pg_search）"
say "普通 Neon/Supabase 不行 —— 需要 paradedb/paradedb 镜像（pg_search）。"
step "选一个持久容器平台部署 paradedb/paradedb:latest-pg17："
say "    Railway  → New Project → Deploy → Docker Image → paradedb/paradedb:latest-pg17"
say "    Render   → New → Web Service → Existing Image → paradedb/paradedb:latest-pg17"
say "    或者复用你已有的 Oracle 主机单独起一套 preview ParadeDB"
step "启动命令必须带: postgres -c shared_preload_libraries=pg_search"
step "设置 POSTGRES_PASSWORD，开启公网连接（TCP proxy / public hostname）"
open_url "https://railway.com/new"
pause "部署完成、拿到公网连接串后按 Enter"
ask_secret PREVIEW_DB_ADMIN_URL "粘贴 admin 连接串（指到 postgres 库，如 postgresql://postgres:PASS@host:PORT/postgres?sslmode=require）："

say "创建 orvilo_preview / orvilo_production 两个数据库…"
for db in orvilo_preview orvilo_production; do
  if pg_admin "CREATE DATABASE \"$db\"" >/dev/null 2>&1; then
    printf '  %s✓ created%s %s\n' "$GREEN" "$RESET" "$db"
  elif try_pg "$(app_db_url "$db")" "SELECT 1" >/dev/null 2>&1; then
    note "  $db 已存在，复用"
  else
    warn "无法自动建库。请在 provider 的 SQL 控制台执行："
    say "    CREATE DATABASE $db;"
    SKIPPED+=("CREATE DATABASE $db")
  fi
done

PREVIEW_DATABASE_URL=$(app_db_url orvilo_preview)
PRODUCTION_DATABASE_URL=$(app_db_url orvilo_production)

if [[ -d node_modules ]] && confirm "现在对两个库跑 bun run db:migrate？"; then
  for pair in "preview:$PREVIEW_DATABASE_URL" "production:$PRODUCTION_DATABASE_URL"; do
    name="${pair%%:*}"; url="${pair#*:}"
    say "迁移 $name …"
    if DATABASE_URL="$url" DATABASE_DRIVER=node bun run db:migrate; then
      printf '  %s✓ migrated%s %s\n' "$GREEN" "$RESET" "$name"
    else
      warn "$name 迁移失败 —— 之后用 db-migrate.yml workflow 补跑"
      SKIPPED+=("migrate $name database")
    fi
  done
else
  warn "跳过迁移（node_modules 不存在或选择跳过）。之后可用 .github/workflows/db-migrate.yml 补跑"
  SKIPPED+=("db:migrate preview + production")
fi

# ── Stage 4 · Upstash Redis + QStash ────────────────────────────────────────
stage "Upstash Redis + QStash"
say "Upstash 一个 Redis 实例同时供 preview/production 用，靠 REDIS_PREFIX 隔离。"
open_url "https://console.upstash.com/redis"
step "Create Database → 复制 rediss:// 连接串（含密码）"
ask_secret REDIS_URL "粘贴 Redis URL（rediss://…）："
step "同一控制台 → QStash 标签页 → 复制 Token 和两个 Signing Key"
ask_secret QSTASH_TOKEN "QSTASH_TOKEN："
ask_secret QSTASH_CURRENT_SIGNING_KEY "QSTASH_CURRENT_SIGNING_KEY："
ask_secret QSTASH_NEXT_SIGNING_KEY "QSTASH_NEXT_SIGNING_KEY（可留空）："

# ── Stage 5 · Cloudflare R2 ─────────────────────────────────────────────────
stage "Cloudflare R2（替代 RustFS）"
open_url "https://dash.cloudflare.com/?to=/:account/r2/new"
step "建两个 bucket：orvilo-preview、orvilo-production"
step "R2 → Manage R2 API Tokens → Create API Token（Object Read & Write，限定这两个 bucket）"
step "记下 Account ID（bucket 页 URL 里有）"
ask R2_ACCOUNT_ID "Account ID："
ask_secret S3_ACCESS_KEY_ID "R2 Access Key ID："
ask_secret S3_SECRET_ACCESS_KEY "R2 Secret Access Key："
S3_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

# ── Stage 6 · 生成应用密钥 ──────────────────────────────────────────────────
stage "生成应用密钥（preview / production 各一套）"
gen_secret() { openssl rand -base64 32; }
PREVIEW_AUTH_SECRET=$(gen_secret)
PROD_AUTH_SECRET=$(gen_secret)
PREVIEW_KEY_VAULTS_SECRET=$(gen_secret)
PROD_KEY_VAULTS_SECRET=$(gen_secret)
say "生成 JWKS（OIDC 签名密钥对）…"
PREVIEW_JWKS_KEY=$(node scripts/generate-oidc-jwk.mjs 2>/dev/null | head -n1)
PROD_JWKS_KEY=$(node scripts/generate-oidc-jwk.mjs 2>/dev/null | head -n1)
if [[ -z "$PREVIEW_JWKS_KEY" || -z "$PROD_JWKS_KEY" ]]; then
  warn "JWKS 生成失败（缺依赖就先 pnpm install）；留空，之后手动跑 node scripts/generate-oidc-jwk.mjs"
  SKIPPED+=("JWKS_KEY ×2")
fi
printf '  %s✓%s 已生成 AUTH_SECRET / KEY_VAULTS_SECRET / JWKS_KEY 各两套\n' "$GREEN" "$RESET"

# ── Stage 7 · 写入 Vercel env ───────────────────────────────────────────────
stage "写入 Vercel 环境变量"
say "Preview 不写 APP_URL —— VERCEL_BRANCH_URL 会自动解析出稳定的分支域名。"
for t in preview production; do
  say "── scope: $t"
  if [[ "$t" == preview ]]; then
    vercel_env DATABASE_URL "$PREVIEW_DATABASE_URL" preview
    vercel_env DATABASE_DRIVER node preview
    vercel_env REDIS_URL "$REDIS_URL" preview
    vercel_env REDIS_PREFIX orvilo-preview preview
    vercel_env REDIS_TLS 1 preview
    vercel_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID" preview
    vercel_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY" preview
    vercel_env S3_ENDPOINT "$S3_ENDPOINT" preview
    vercel_env S3_BUCKET orvilo-preview preview
    vercel_env S3_REGION auto preview
    vercel_env S3_SET_ACL 0 preview
    vercel_env AUTH_SECRET "$PREVIEW_AUTH_SECRET" preview
    vercel_env KEY_VAULTS_SECRET "$PREVIEW_KEY_VAULTS_SECRET" preview
    [[ -n "$PREVIEW_JWKS_KEY" ]] && vercel_env JWKS_KEY "$PREVIEW_JWKS_KEY" preview
    vercel_env QSTASH_TOKEN "$QSTASH_TOKEN" preview
    vercel_env QSTASH_CURRENT_SIGNING_KEY "$QSTASH_CURRENT_SIGNING_KEY" preview
    [[ -n "$QSTASH_NEXT_SIGNING_KEY" ]] && vercel_env QSTASH_NEXT_SIGNING_KEY "$QSTASH_NEXT_SIGNING_KEY" preview
  else
    vercel_env DATABASE_URL "$PRODUCTION_DATABASE_URL" production
    vercel_env DATABASE_DRIVER node production
    vercel_env REDIS_URL "$REDIS_URL" production
    vercel_env REDIS_PREFIX orvilo-prod production
    vercel_env REDIS_TLS 1 production
    vercel_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID" production
    vercel_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY" production
    vercel_env S3_ENDPOINT "$S3_ENDPOINT" production
    vercel_env S3_BUCKET orvilo-production production
    vercel_env S3_REGION auto production
    vercel_env S3_SET_ACL 0 production
    vercel_env AUTH_SECRET "$PROD_AUTH_SECRET" production
    vercel_env KEY_VAULTS_SECRET "$PROD_KEY_VAULTS_SECRET" production
    [[ -n "$PROD_JWKS_KEY" ]] && vercel_env JWKS_KEY "$PROD_JWKS_KEY" production
    vercel_env QSTASH_TOKEN "$QSTASH_TOKEN" production
    vercel_env QSTASH_CURRENT_SIGNING_KEY "$QSTASH_CURRENT_SIGNING_KEY" production
    [[ -n "$QSTASH_NEXT_SIGNING_KEY" ]] && vercel_env QSTASH_NEXT_SIGNING_KEY "$QSTASH_NEXT_SIGNING_KEY" production
  fi
done

# ── Stage 8 · GitHub secrets + variables ────────────────────────────────────
stage "写入 GitHub secrets / variables"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
set_secret PREVIEW_DATABASE_URL "$PREVIEW_DATABASE_URL"
set_secret PREVIEW_DB_ADMIN_URL "$PREVIEW_DB_ADMIN_URL"
set_secret PRODUCTION_DATABASE_URL "$PRODUCTION_DATABASE_URL"
say "可选开关：每 PR 独立数据库（preview-db.yml / preview-cleanup.yml）"
if confirm "现在开启 PREVIEW_EPHEMERAL_DB_ENABLED？"; then
  set_var PREVIEW_EPHEMERAL_DB_ENABLED true
else
  note "之后想开：gh variable set PREVIEW_EPHEMERAL_DB_ENABLED --body true"
fi
say "建议：GitHub → Settings → Environments → 建 production environment"
say "      并加 required reviewers（db-migrate.yml 的 production 门禁用它）"

# ── Stage 9 · 验证 ──────────────────────────────────────────────────────────
stage "验证"
say "推一个分支验证整条链路："
say "    git checkout -b test/vercel-preview && git push -u origin HEAD"
say "Vercel 会自动构建出 Preview URL；部署成功后 preview-smoke 会跑 @smoke。"
step "打开 PR → 检查 Checks：Vercel Preview + Preview Smoke"
say "手动对任意 preview 跑环境自检："
say "    BASE_URL=https://<preview>.vercel.app bun scripts/ci/checkPreviewEnv.mts"
say "之后本机开发不再需要 Docker：.env 里改成云端值即可（见 .env.example.development Mode A）"
if confirm "把 preview 的云端连接写进本地 .env（Mode A 云开发）？"; then
  write_env DATABASE_URL "$PREVIEW_DATABASE_URL"
  write_env DATABASE_DRIVER node
  write_env REDIS_URL "$REDIS_URL"
  write_env REDIS_PREFIX orvilo-preview
  write_env REDIS_TLS 1
  write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
  write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
  write_env S3_ENDPOINT "$S3_ENDPOINT"
  write_env S3_BUCKET orvilo-preview
  write_env S3_REGION auto
  write_env S3_SET_ACL 0
fi

finish
