#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# ── Wizard-local helpers ───────────────────────────────────────────────────

# vercel_env KEY VALUE TARGET [BRANCH] — upsert a Vercel env var via REST API.
vercel_env() {
  local key="$1" value="$2" target="$3" branch="${4:-}"
  if [[ -z "${VERCEL_TOKEN:-}" || -z "${VERCEL_PROJECT_ID:-}" ]]; then
    SKIPPED+=("Vercel env $key [$target]")
    warn "缺少 VERCEL_TOKEN/PROJECT_ID，跳过 $key —— 之后手动在 Vercel 后台添加"
    return
  fi
  local qs="upsert=true"
  [[ -n "${VERCEL_ORG_ID:-}" ]] && qs="${qs}&teamId=${VERCEL_ORG_ID}"
  local payload
  if [[ -n "$branch" ]]; then
    payload=$(jq -n --arg k "$key" --arg v "$value" --arg t "$target" --arg b "$branch" \
      '{key:$k, value:$v, type:"sensitive", target:[$t], gitBranch:$b}')
  else
    payload=$(jq -n --arg k "$key" --arg v "$value" --arg t "$target" \
      '{key:$k, value:$v, type:"sensitive", target:[$t]}')
  fi
  if curl -fsS -X POST \
      "https://api.vercel.com/v10/projects/${VERCEL_PROJECT_ID}/env?${qs}" \
      -H "Authorization: Bearer ${VERCEL_TOKEN}" \
      -H 'Content-Type: application/json' \
      -d "$payload" >/dev/null; then
    printf '  %s✓ 写入%s Vercel env %s [%s%s]\n' "$GREEN" "$RESET" "$key" "$target" "${branch:+ @$branch}"
  else
    SKIPPED+=("Vercel env $key [$target]")
    warn "写入 $key 失败 —— 之后在 Vercel 后台手动添加"
  fi
}

# try_pg URL SQL — run SQL against a specific connection URL (psql → bun+pg).
try_pg() {
  local url="$1" sql="$2" ca_file=""
  if command -v psql >/dev/null 2>&1; then
    local psql_url
    if [[ -n "${DATABASE_SSL_CA:-}" ]]; then
      ca_file=$(mktemp)
      CA_VALUE="$DATABASE_SSL_CA" node -e '
        process.stdout.write(process.env.CA_VALUE.replaceAll("\\n", "\n"));
      ' > "$ca_file"
      chmod 600 "$ca_file"
    fi
    psql_url=$(DB_URL="$url" DB_HOST="${PREVIEW_DB_TLS_HOST:-}" CA_FILE="$ca_file" node -e '
      const parsed = new URL(process.env.DB_URL);
      if (process.env.DB_HOST) parsed.hostname = process.env.DB_HOST;
      parsed.searchParams.delete("uselibpqcompat");
      if (process.env.CA_FILE) {
        parsed.searchParams.set("sslmode", "verify-full");
        parsed.searchParams.set("sslrootcert", process.env.CA_FILE);
      }
      process.stdout.write(parsed.toString());
    ')
    local status=0
    psql "$psql_url" -v ON_ERROR_STOP=1 -tAc "$sql" || status=$?
    [[ -z "$ca_file" ]] || rm -f "$ca_file"
    return "$status"
  fi
  if [[ -d node_modules ]]; then
    PG_SQL="$sql" DB_URL="$url" DB_HOST="${PREVIEW_DB_TLS_HOST:-}" \
      DB_CA="${DATABASE_SSL_CA:-}" bun -e '
      import pg from "pg";
      const url = new URL(process.env.DB_URL);
      if (process.env.DB_HOST) url.hostname = process.env.DB_HOST;
      let ssl;
      if (process.env.DB_CA) {
        for (const key of ["sslmode", "sslcert", "sslkey", "sslrootcert", "uselibpqcompat"]) {
          url.searchParams.delete(key);
        }
        ssl = {
          ca: process.env.DB_CA.replaceAll("\\n", "\n"),
          rejectUnauthorized: true,
        };
      }
      const c = new pg.Client({ connectionString: url.href, ssl });
      await c.connect();
      await c.query(process.env.PG_SQL);
      await c.end();
    '
    return
  fi
  return 1
}

# pg_admin SQL — run SQL against PREVIEW_DB_ADMIN_URL.
pg_admin() { try_pg "$PREVIEW_DB_ADMIN_URL" "$1"; }

# admin_db_url DBNAME — derive an admin URL for one database without logging it.
admin_db_url() {
  local url
  url=$(ADMIN_URL="$PREVIEW_DB_ADMIN_URL" DB_NAME="$1" node -e '
    const parsed = new URL(process.env.ADMIN_URL);
    parsed.pathname = `/${process.env.DB_NAME}`;
    process.stdout.write(parsed.toString());
  ')
  # The Node runtime receives DATABASE_SSL_CA separately. Keep the compatibility
  # flag on its URL; psql removes that flag and verifies the private CA in try_pg.
  if [[ "$url" == *"sslmode=require"* && "$url" != *"uselibpqcompat="* ]]; then
    if [[ "$url" == *"?"* ]]; then url="${url}&uselibpqcompat=true"; else url="${url}?uselibpqcompat=true"; fi
  fi
  echo "$url"
}

gen_secret() { openssl rand -base64 32; }

banner "Orvilo 云开发环境迁移"

# ── Stage 1 · 前置检查 + Vercel link ────────────────────────────────────────
stage "前置检查 + 连接 Vercel 项目"
say "检查本机工具，并把仓库 link 到 Vercel project。"
for cmd in gh bun curl jq; do
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$cmd"
  else
    warn "缺少 $cmd"
    SKIPPED+=("install $cmd")
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "gh 未登录 —— 先跑 gh auth login，否则 GitHub secrets 只能手动设置"
fi
if ! command -v vercel >/dev/null 2>&1; then
  say "未找到 vercel CLI，尝试通过 bun 安装…"
  bun install -g vercel@latest || warn "vercel CLI 安装失败"
fi
if [[ ! -f .vercel/project.json ]]; then
  say "把当前目录 link 到 Vercel project（还没有 project 就先在网页端 Import：）"
  open_url "https://vercel.com/new"
  step "Import alexj11324/orvilo1 → Root Directory 保持仓库根目录"
  step "Framework 选 Next.js（自动识别）；Production Branch = main"
  pause "project 建好后按 Enter，我会执行 vercel link"
  vercel link --yes || warn "vercel link 失败，请手动跑 vercel link"
fi
if [[ -f .vercel/project.json ]]; then
  VERCEL_ORG_ID=$(jq -r '.orgId' .vercel/project.json)
  VERCEL_PROJECT_ID=$(jq -r '.projectId' .vercel/project.json)
  say "已连接：orgId=${VERCEL_ORG_ID} projectId=${VERCEL_PROJECT_ID}"
fi
open_url "https://vercel.com/account/tokens"
step "创建一个 Account-scoped token（名字随意，如 orvilo-ci）"
ask_secret VERCEL_TOKEN "粘贴 Vercel token："

# ── Stage 2 · Deployment Protection 绕过密钥 ────────────────────────────────
stage "Deployment Protection（Preview 自动化绕过）"
say "Preview 部署默认有登录保护，CI 里的 Playwright 需要 bypass secret。"
open_url "https://vercel.com"
step "Project → Settings → Deployment Protection"
step "确认 'Vercel Authentication' 对 Preview 开启"
step "在 'Protection Bypass for Automation' 生成一个 secret"
ask_secret VERCEL_AUTOMATION_BYPASS_SECRET "粘贴 bypass secret："
set_secret VERCEL_AUTOMATION_BYPASS_SECRET "$VERCEL_AUTOMATION_BYPASS_SECRET"

# ── Stage 3 · 远程 ParadeDB ─────────────────────────────────────────────────
stage "远程 ParadeDB（pgvector + pg_search）"
say "普通 Neon/Supabase 不行 —— 需要 paradedb/paradedb 镜像（pg_search）。"
say "当前已 provision：OCI Always-Free 主机上独立容器 orvilo-preview-pg"
say "（paradedb/paradedb:latest-pg17，公网端口 25432，SSL=on 私有 CA 证书）。"
say "若要重建或迁到别的平台，参考命令："
say "    docker run -d --name orvilo-preview-pg --restart always --memory 2g \\"
say "      -p 25432:5432 -e POSTGRES_DB=orvilo_preview \\"
say "      -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=<strong> \\"
say "      -v orvilo-preview-pgdata:/var/lib/postgresql/data \\"
say "      -v ~/orvilo-preview/pgssl:/pgssl:ro \\"
say "      paradedb/paradedb:latest-pg17 \\"
say "      -c ssl=on -c ssl_cert_file=/pgssl/server.crt \\"
say "      -c ssl_key_file=/pgssl/server.key \\"
say "      -c shared_buffers=256MB -c max_connections=50"
note "记得同步开 NSG/安全组 + 主机防火墙对应端口"
ask_secret PREVIEW_DB_ADMIN_URL "粘贴 admin 连接串（指到 postgres 库，如 postgresql://postgres:PASS@host:25432/postgres?sslmode=require）："
ask_secret DATABASE_SSL_CA "粘贴 PostgreSQL 私有 CA PEM（可用 \\n 表示换行）："
[[ -n "$DATABASE_SSL_CA" ]] || { warn "DATABASE_SSL_CA 不能为空"; exit 1; }
ask PREVIEW_DB_TLS_HOST "PostgreSQL 证书里的 DNS 主机名："
[[ -n "$PREVIEW_DB_TLS_HOST" ]] || { warn "PREVIEW_DB_TLS_HOST 不能为空"; exit 1; }
PREVIEW_DB_ADMIN_URL=$(DATABASE_URL="$PREVIEW_DB_ADMIN_URL" DATABASE_HOST="$PREVIEW_DB_TLS_HOST" node -e '
  const url = new URL(process.env.DATABASE_URL);
  url.hostname = process.env.DATABASE_HOST;
  url.searchParams.delete("uselibpqcompat");
  url.searchParams.set("sslmode", "require");
  process.stdout.write(url.href);
')

say "创建 orvilo_preview 数据库…"
if pg_admin 'CREATE DATABASE "orvilo_preview"' >/dev/null 2>&1; then
  printf '  %s✓ created%s orvilo_preview\n' "$GREEN" "$RESET"
elif try_pg "$(admin_db_url orvilo_preview)" "SELECT 1" >/dev/null 2>&1; then
  note "  orvilo_preview 已存在，复用"
else
  warn "无法自动建库。请在 provider 的 SQL 控制台执行 CREATE DATABASE orvilo_preview;"
  SKIPPED+=("CREATE DATABASE orvilo_preview")
fi

PREVIEW_DB_MIGRATION_URL=$(admin_db_url orvilo_preview)
PREVIEW_KEY_VAULTS_SECRET=$(_existing KEY_VAULTS_SECRET || true)
[[ -n "$PREVIEW_KEY_VAULTS_SECRET" ]] || PREVIEW_KEY_VAULTS_SECRET=$(gen_secret)
if [[ -d node_modules ]] && confirm "现在对 Preview 库跑 bun run db:migrate？"; then
  if DATABASE_URL="$PREVIEW_DB_MIGRATION_URL" DATABASE_DRIVER=node \
    DATABASE_SSL_CA="$DATABASE_SSL_CA" KEY_VAULTS_SECRET="$PREVIEW_KEY_VAULTS_SECRET" \
    bun run db:migrate; then
    printf '  %s✓ migrated%s preview\n' "$GREEN" "$RESET"
  else
    warn "Preview 迁移失败 —— 之后用 db-migrate.yml workflow 补跑"
    SKIPPED+=("migrate preview database")
  fi
else
  warn "跳过迁移（node_modules 不存在或选择跳过）。之后可用 .github/workflows/db-migrate.yml 补跑"
  SKIPPED+=("db:migrate preview")
fi
say "为应用创建只对 orvilo_preview 有 CONNECT/表与序列读写权限的非管理员 LOGIN role。"
ask_secret PREVIEW_DATABASE_URL "粘贴该最小权限角色的 Preview 连接串："
ask_secret PREVIEW_TEST_DATABASE_URL "粘贴受限 CI role 的 Preview 连接串："
ADMIN_USERNAME=$(ADMIN_URL="$PREVIEW_DB_ADMIN_URL" node -e 'process.stdout.write(new URL(process.env.ADMIN_URL).username)')
APP_USERNAME=$(APP_URL="$PREVIEW_DATABASE_URL" node -e 'process.stdout.write(new URL(process.env.APP_URL).username)')
[[ -n "$APP_USERNAME" && "$APP_USERNAME" != "$ADMIN_USERNAME" ]] || {
  warn "Preview 应用连接串不能继续使用管理员角色"
  exit 1
}
TEST_USERNAME=$(APP_URL="$PREVIEW_TEST_DATABASE_URL" node -e 'process.stdout.write(new URL(process.env.APP_URL).username)')
[[ -n "$TEST_USERNAME" && "$TEST_USERNAME" != "$ADMIN_USERNAME" && "$TEST_USERNAME" != "$APP_USERNAME" ]] || {
  warn "Preview CI 连接串必须使用独立的非管理员角色"
  exit 1
}
RESTRICTED_ROLE_CHECK="DO \$role_check\$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_catalog.pg_roles
    WHERE rolname = current_user
      AND (rolsuper OR rolcreatedb OR rolcreaterole OR rolreplication OR rolbypassrls)
  ) OR has_schema_privilege(current_user, 'public', 'CREATE') THEN
    RAISE EXCEPTION 'current role is not restricted';
  END IF;
END
\$role_check\$;"
try_pg "$PREVIEW_DATABASE_URL" "$RESTRICTED_ROLE_CHECK" >/dev/null || {
  warn "Preview 应用连接串无法连接，或该角色仍有管理员/schema CREATE 权限"
  exit 1
}
try_pg "$PREVIEW_TEST_DATABASE_URL" "$RESTRICTED_ROLE_CHECK" >/dev/null || {
  warn "Preview CI 连接串无法连接，或该角色仍有管理员/schema CREATE 权限"
  exit 1
}

# ── Stage 4 · Redis ─────────────────────────────────────────────────────────
stage "Redis（与 ParadeDB 同机的独立容器）"
say "公网 Redis 必须只开放 TLS 端口，并让应用固定信任专用 CA。"
say "不要把带密码的 redis:// 明文端口暴露到公网。"
say "推荐让 TLS 终止层监听公网 26380，并只在 Docker 内网连接 Redis 6379。"
say "切换验证通过后，移除 Redis 容器的公网 26379 映射及对应防火墙/NSG 规则。"
ask_secret REDIS_URL "粘贴 Redis TLS URL（rediss://default:<pass>@<host>:26380）："
ask_secret REDIS_TLS_CA "粘贴 Redis CA PEM（可用 \\n 表示换行）："
[[ "$REDIS_URL" == rediss://* ]] || { warn "REDIS_URL 必须使用 rediss://"; exit 1; }
[[ -n "$REDIS_TLS_CA" ]] || { warn "REDIS_TLS_CA 不能为空"; exit 1; }
note "QStash 已跳过 —— agent 异步运行时正迁往 Hatchet，不配 QStash 时步骤同步执行。"

# ── Stage 5 · Cloudflare R2 ─────────────────────────────────────────────────
stage "Cloudflare R2（替代 RustFS）"
open_url "https://dash.cloudflare.com/?to=/:account/r2/new"
step "建立 bucket：orvilo-preview"
step "R2 → Manage R2 API Tokens → Create API Token（Object Read & Write，只限定 orvilo-preview）"
step "记下 Account ID（bucket 页 URL 里有）"
ask R2_ACCOUNT_ID "Account ID："
ask_secret S3_ACCESS_KEY_ID "R2 Access Key ID："
ask_secret S3_SECRET_ACCESS_KEY "R2 Secret Access Key："
S3_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

# ── Stage 6 · 生成应用密钥 ──────────────────────────────────────────────────
stage "生成 Preview 应用密钥"
PREVIEW_AUTH_SECRET=$(_existing AUTH_SECRET || true)
[[ -n "$PREVIEW_AUTH_SECRET" ]] || PREVIEW_AUTH_SECRET=$(gen_secret)
say "生成 JWKS（OIDC 签名密钥对）…"
PREVIEW_JWKS_KEY=$(_existing JWKS_KEY || true)
if [[ -z "$PREVIEW_JWKS_KEY" ]]; then
  if generated_jwks=$(node scripts/generate-oidc-jwk.mjs 2>/dev/null | head -n1); then
    PREVIEW_JWKS_KEY="$generated_jwks"
  else
    warn "JWKS 生成失败（缺依赖就先 pnpm install）；之后手动跑 node scripts/generate-oidc-jwk.mjs"
    SKIPPED+=("JWKS_KEY")
  fi
fi
printf '  %s✓%s Preview AUTH_SECRET / KEY_VAULTS_SECRET 已就绪\n' "$GREEN" "$RESET"

# ── Stage 7 · 写入 Vercel env ───────────────────────────────────────────────
stage "写入 Vercel 环境变量"
say "只写 Preview scope；production 凭据必须走独立发布流程。"
say "Preview 不写 APP_URL —— VERCEL_BRANCH_URL 会自动解析出稳定的分支域名。"
vercel_env DATABASE_URL "$PREVIEW_DATABASE_URL" preview
vercel_env DATABASE_DRIVER node preview
vercel_env DATABASE_SSL_CA "$DATABASE_SSL_CA" preview
vercel_env REDIS_URL "$REDIS_URL" preview
vercel_env REDIS_PREFIX orvilo-preview preview
vercel_env REDIS_TLS 1 preview
vercel_env REDIS_TLS_CA "$REDIS_TLS_CA" preview
vercel_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID" preview
vercel_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY" preview
vercel_env S3_ENDPOINT "$S3_ENDPOINT" preview
vercel_env S3_BUCKET orvilo-preview preview
vercel_env S3_REGION auto preview
vercel_env S3_SET_ACL 0 preview
vercel_env AUTH_SECRET "$PREVIEW_AUTH_SECRET" preview
vercel_env KEY_VAULTS_SECRET "$PREVIEW_KEY_VAULTS_SECRET" preview
[[ -n "$PREVIEW_JWKS_KEY" ]] && vercel_env JWKS_KEY "$PREVIEW_JWKS_KEY" preview

# ── Stage 8 · GitHub secrets + variables ────────────────────────────────────
stage "写入 GitHub secrets / variables"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
set_secret PREVIEW_DATABASE_URL "$PREVIEW_DATABASE_URL"
set_secret PREVIEW_TEST_DATABASE_URL "$PREVIEW_TEST_DATABASE_URL"
set_secret PREVIEW_DB_ADMIN_URL "$PREVIEW_DB_ADMIN_URL"
set_secret PREVIEW_DATABASE_SSL_CA "$DATABASE_SSL_CA"
set_secret PREVIEW_KEY_VAULTS_SECRET "$PREVIEW_KEY_VAULTS_SECRET"
set_var PREVIEW_DB_TLS_HOST "$PREVIEW_DB_TLS_HOST"
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  configured_secrets=$(gh secret list --json name --jq '.[].name')
  for required_secret in ORACLE_HOST ORACLE_SSH_KEY ORACLE_SSH_KNOWN_HOSTS; do
    if ! grep -qx "$required_secret" <<< "$configured_secrets"; then
      warn "缺少 GitHub secret $required_secret；Preview Smoke/E2E 不会启动"
      SKIPPED+=("GitHub secret $required_secret")
    fi
  done
fi
say "可选开关：每 PR 独立数据库（preview-db.yml / preview-cleanup.yml）"
if confirm "现在开启 PREVIEW_EPHEMERAL_DB_ENABLED？"; then
  set_var PREVIEW_EPHEMERAL_DB_ENABLED true
else
  note "之后想开：gh variable set PREVIEW_EPHEMERAL_DB_ENABLED --body true"
fi
say "Production 后续单独配置：独立数据库角色、独立 R2 token，并在 GitHub environment 加 required reviewers。"

# ── Stage 9 · 验证 ──────────────────────────────────────────────────────────
stage "验证"
say "推一个分支验证整条链路："
say "    git checkout -b test/vercel-preview && git push -u origin HEAD"
say "Vercel 会自动构建出 Preview URL；部署成功后 preview-smoke 会跑 @smoke。"
step "打开 PR → 检查 Checks：Vercel Preview + Preview Smoke"
say "手动对任意 preview 跑环境自检："
say "    BASE_URL=https://<preview>.vercel.app bun scripts/ci/checkPreviewEnv.mts"
say "之后本机开发不再需要 Docker：.env 里改成云端值即可（见 .env.example.development Mode A）"
if confirm "把 preview 的云端连接写进本地 .env（Mode A 云开发）？"; then
  write_env DATABASE_URL "$PREVIEW_DATABASE_URL"
  write_env DATABASE_DRIVER node
  write_env DATABASE_SSL_CA "$DATABASE_SSL_CA"
  write_env KEY_VAULTS_SECRET "$PREVIEW_KEY_VAULTS_SECRET"
  write_env AUTH_SECRET "$PREVIEW_AUTH_SECRET"
  write_env REDIS_URL "$REDIS_URL"
  write_env REDIS_PREFIX orvilo-preview
  write_env REDIS_TLS 1
  write_env REDIS_TLS_CA "$REDIS_TLS_CA"
  write_env S3_ACCESS_KEY_ID "$S3_ACCESS_KEY_ID"
  write_env S3_SECRET_ACCESS_KEY "$S3_SECRET_ACCESS_KEY"
  write_env S3_ENDPOINT "$S3_ENDPOINT"
  write_env S3_BUCKET orvilo-preview
  write_env S3_REGION auto
  write_env S3_SET_ACL 0
fi

finish
